version: "3"

services:




# zzzzzzzzz

  python:
    # build: .
    build: ../python
    # build: ./
    # build: ../microservices/tct-demo
    restart: always
    ports:
      - 5000:5000
      # command: npm run start:dev
  #     # environment:
  #     # PORT: ${TCT_PORT}




      # services:
      #   jenkins:
      #     image: jenkins/jenkins:lts
      #     ports:
      #       - "8080:8080"
      #     volumes:
      #       - jenkins_home:/var/jenkins_home

      #   sonarqube:
      #     image: sonarqube:latest
      #     ports:
      #       - "9000:9000"
      #     environment:
      #       - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      #     volumes:
      #       - sonarqube_data:/opt/sonarqube/data
      #       - sonarqube_extensions:/opt/sonarqube/extensions

      # volumes:
      #   jenkins_home:
      #   sonarqube_data:
      #   sonarqube_extensions:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
