pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube']])
            }
        }

        stage('Build') {
            steps {
                // git branch: 'main', url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube'
                sh 'echo 123'
            // sh 'python3 ops.py'
            }
        }

        stage('Test') {
            steps {
                // sh 'apt-get update'
                // sh 'apt-get install -y python3'
                // sh 'python3 -m pip install -r requirements.txt'
                sh 'echo 123'
            // sh 'python3 -m pytest'
            }
        }

        stage('sonar-scanner') {  steps {
                // sh 'apt-get update'
                // sh 'apt-get install -y python3'
                // sh 'python3 -m pip install -r requirements.txt'
                sh 'echo 123'
            // sh 'python3 -m pytest'
            }
            // def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
            // withCredentials([string(credentialsId: 'SonarQube', variable: 'sonarLogin')]) {
            //     sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.language=java -Dsonar.java.binaries=."
            // }
        }

    // stage('SonarQube Analysis') {
    //     def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
    //     withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
    //         sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=gs-gradle -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=complete/src/main/ -Dsonar.tests=complete/src/test/ -Dsonar.language=java -Dsonar.java.binaries=."
    //     }
    // }
    }
}
