pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube']])
            }
        }
        stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube'
                sh 'python3 ops.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 -m pytest'
            }
        }
    }
}
