pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube']])
            }
        }
        stage('Build') {
            steps {
                // git branch: 'main', url: 'https://github.com/vvn20206205/python_docker_jenkins_sonarqube'

                // sh 'apt-get update'

                // sh 'apt-get install -y python3'
                sh 'echo 123'
            // sh 'python3 ops.py'
            }
        }
        stage('Test') {
            steps {
                // sh 'apt-get update'

                // sh 'apt-get install -y python3'

                // sh 'python3 -m pip install -r requirements.txt'
                sh 'echo 123'

            // sh 'python3 -m pytest'
            }
        }
    }
}
